### ISSUE TITLE
STATS - Optimize

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/tumeplay#176]
- [x] Number of individuals who have 80% right answers on the App quiz
- [x] Number of individuals who come back to the app and use it again (ceux qui refont quizz) 
- [x] Number of users who spend 3 minutes or more on the App Quiz
- [x] Number of users who spend 3 minutes or more on the App Quiz (toutes les personnes qui ont passé plus de 3 mins sur les quizz au cumul)
- [x] Time spent on quizz (-25 ans et + 25ans)
- [x] Number of youth (-25 ans et + 25ans) who took a test
- [x] Number of young people who answered at least 1 set of questions on the App quiz
- [x] Number of young people who ordered at least 1 basket
- [x] Number of youths who ordered at least 2 different baskets
- [x] Number of standard boxes sent 
- [x] Number of bespoke boxes sent
- [x] Total number of external condoms distributed by the programme
- [x] Total number of internal condoms distributed by the programme
- [x] Total number of latex squares distributed by the program
- [x] Total number of lubricant pods dispensed by the program (in total and per type of lubricant pod)
- [x] Average time spent on the quiz by user calculated as a ratio of time spent on quiz versus number of users

**Comment by ClementNumericite** [comment]
Date : 14/10/2021

Utilisateurs qui reviennent : 96 / 1184
Utilisateurs avec +80% de bonnes réponses : 664 / 1184
Utilisateurs ayant passé plus de 3 minutes sur les quiz : 740 / 1184
Utilisateurs -25 ayant réalisé un quiz : 1027
Utilisateurs +25 ayant réalisé un quiz : 157
Temps moyen -25 sur les quiz : 1.649084321475626 minutes
Temps moyen +25 sur les quiz : 1.9588785046728971 minutes
Jeune ayant commandé + d'une fois : 483
Jeune ayant commandé au moins 2 box différentes : 399
Nombre de box "classiques" envoyées : 3531
Nombre de box sur mesure envoyées : 28
Nombre de préservatifs internes distribués : 7062
Nombre de préservatifs externes distribués : 13770
Nombre de carrés de latex distribués : 3390
Nombre de lubrifiants distribués : 12524
