### ISSUE TITLE
URGENT - Combien de commande par type de boîte depuis le 05OCT

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/tumeplay#204]
pour qui ? Maxime
quoi ? Savoir combien de boîte 1, 2 et 3 ont été envoyées depuis le 05OCT.
pourquoi ? on doit mettre à jour les stocks de boîte dans le BO.

**Comment by ClementNumericite** [comment]
Fait le 02/11/2021 : 

BOX 1  :  190
BOX 2  :  173
BOX 3  :  371

(rappel : depuis le 05 oct)
